export const CATEGORIES = [
  'VEGGIES',
  'FRUIT',
  'MEAT & FISH',
  'DELI, DAIRY, EGGS',
  'FROZEN',
  'DRY GOODS',
  'BAKING, SPICES & OILS',
  'PREPARED FOODS',
  'PHARMACY / OTC',
  'TARGET / AMAZON / COSTCO',
  'COSTCO BULK FOODS',
  'RANCH 99 / WEEE / BERKELEY BOWL'
];

export const MATCH_CONFIDENCE = {
  EXACT: 1,
  NORMALIZED_EXACT: 0.99,
  SINGULAR_PLURAL: 0.98,
  TOKEN_REORDER: 0.96
};

export const DEFAULT_FUZZY_THRESHOLD = 0.93;

export const DEFAULT_CATEGORY_CONFIDENCE_THRESHOLD = 0.8;
